
var a;a||(a=typeof Module !== 'undefined' ? Module : {});var c={},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);var g=!1,h=!1,k=!1,l=!1;g="object"===typeof window;h="function"===typeof importScripts;k="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;l=!g&&!k&&!h;var m="",n,p,q,r,t;
if(k)m=h?require("path").dirname(m)+"/":__dirname+"/",n=function(b,d){r||(r=require("fs"));t||(t=require("path"));b=t.normalize(b);return r.readFileSync(b,d?null:"utf8")},q=function(b){b=n(b,!0);b.buffer||(b=new Uint8Array(b));b.buffer||u("Assertion failed: undefined");return b},1<process.argv.length&&process.argv[1].replace(/\\/g,"/"),process.argv.slice(2),"undefined"!==typeof module&&(module.exports=a),process.on("uncaughtException",function(b){throw b;}),process.on("unhandledRejection",u),a.inspect=
function(){return"[Emscripten Module object]"};else if(l)"undefined"!=typeof read&&(n=function(b){return read(b)}),q=function(b){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(b));b=read(b,"binary");"object"===typeof b||u("Assertion failed: undefined");return b},"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(g||h)h?m=self.location.href:document.currentScript&&
(m=document.currentScript.src),m=0!==m.indexOf("blob:")?m.substr(0,m.lastIndexOf("/")+1):"",n=function(b){var d=new XMLHttpRequest;d.open("GET",b,!1);d.send(null);return d.responseText},h&&(q=function(b){var d=new XMLHttpRequest;d.open("GET",b,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)}),p=function(b){var d=v,e=new XMLHttpRequest;e.open("GET",w,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?d(e.response):b()};e.onerror=
b;e.send(null)};a.print||console.log.bind(console);var x=a.printErr||console.warn.bind(console);for(f in c)c.hasOwnProperty(f)&&(a[f]=c[f]);c=null;var y=0,noExitRuntime;a.noExitRuntime&&(noExitRuntime=a.noExitRuntime);var z=!1;"undefined"!==typeof TextDecoder&&new TextDecoder("utf8");"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var A,B,C,D=a.INITIAL_MEMORY||16777216;a.buffer?A=a.buffer:A=new ArrayBuffer(D);D=A.byteLength;var E=A;A=E;a.HEAP8=new Int8Array(E);a.HEAP16=new Int16Array(E);
a.HEAP32=C=new Int32Array(E);a.HEAPU8=B=new Uint8Array(E);a.HEAPU16=new Uint16Array(E);a.HEAPU32=new Uint32Array(E);a.HEAPF32=new Float32Array(E);a.HEAPF64=new Float64Array(E);C[208]=4999008;function F(b){for(;0<b.length;){var d=b.shift();if("function"==typeof d)d(a);else{var e=d.j;"number"===typeof e?void 0===d.i?a.dynCall_v(e):a.dynCall_vi(e,d.i):e(void 0===d.i?null:d.i)}}}var G=[],H=[],I=[],J=[];function K(){var b=a.preRun.shift();G.unshift(b)}var L=0,M=null,N=null;a.preloadedImages={};
a.preloadedAudios={};function u(b){if(a.onAbort)a.onAbort(b);x(b);z=!0;throw"abort("+b+"). Build with -s ASSERTIONS=1 for more info.";}var w=null;H.push({j:function(){O()}});w="lexer.min.emcc.js.mem";
var P={Int8Array:Int8Array,Int16Array:Int16Array,Int32Array:Int32Array,Uint8Array:Uint8Array,Uint16Array:Uint16Array},Q={a:u,b:function(b){y=b},c:function(){return y},d:function(){return B.length},e:function(b,d,e){B.copyWithin(b,d,d+e)},f:function(){u("OOM")},g:1024,h:function(){x("missing function: __heap_base");u(-1)}};// EMSCRIPTEN_START_ASM
var R=a["asm"]// EMSCRIPTEN_END_ASM
(P,Q,A);a.___errno_location=R.___errno_location;var O=a.__apply_relocations=R.__apply_relocations;
a._ai=R._ai;a._e=R._e;a._ee=R._ee;a._ele=R._ele;a._els=R._els;a._emscripten_get_sbrk_ptr=R._emscripten_get_sbrk_ptr;a._es=R._es;a._free=R._free;a._id=R._id;a._ie=R._ie;a._ip=R._ip;a._is=R._is;a._it=R._it;a._malloc=R._malloc;a._memcpy=R._memcpy;a._memset=R._memset;a._parse=R._parse;a._re=R._re;a._ri=R._ri;a._sa=R._sa;a._se=R._se;a._setSource=R._setSource;a._ss=R._ss;a.stackAlloc=R.stackAlloc;a.stackRestore=R.stackRestore;a.stackSave=R.stackSave;a.asm=R;
if(w){var S=w;if(String.prototype.startsWith?!S.startsWith("data:application/octet-stream;base64,"):0!==S.indexOf("data:application/octet-stream;base64,")){var T=w;w=a.locateFile?a.locateFile(T,m):m+T}if(k||l){var U=q(w);B.set(U,8)}else{L++;a.monitorRunDependencies&&a.monitorRunDependencies(L);var v=function(b){b.byteLength&&(b=new Uint8Array(b));B.set(b,8);a.memoryInitializerRequest&&delete a.memoryInitializerRequest.response;L--;a.monitorRunDependencies&&a.monitorRunDependencies(L);0==L&&(null!==
M&&(clearInterval(M),M=null),N&&(b=N,N=null,b()))},V=function(){p(function(){throw Error("could not load memory initializer "+w);})};if(a.memoryInitializerRequest){var W=function(){var b=a.memoryInitializerRequest,d=b.response;200!==b.status&&0!==b.status?(console.warn("a problem seems to have happened with Module.memoryInitializerRequest, status: "+b.status+", retrying "+w),V()):v(d)};a.memoryInitializerRequest.response?setTimeout(W,0):a.memoryInitializerRequest.addEventListener("load",W)}else V()}}var X;
N=function Y(){X||Z();X||(N=Y)};
function Z(){function b(){if(!X&&(X=!0,a.calledRun=!0,!z)){F(H);F(I);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;){var d=a.postRun.shift();J.unshift(d)}F(J)}}if(!(0<L)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)K();F(G);0<L||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);b()},1)):b())}}a.run=Z;
if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();noExitRuntime=!0;Z();

